services:
  postgres:
    image: postgres:16
    container_name: shopapi-db
    environment:
      POSTGRES_DB: shopapi
      POSTGRES_USER: shopapi
      POSTGRES_PASSWORD: shopapi
    ports:
      - "5432:5432"
    volumes:
      - shopapi-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: shopapi-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shopapi.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"


volumes:
  shopapi-data: