spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:shopapi}
    username: ${DB_USER:shopapi}
    password: ${DB_PASSWORD:shopapi}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:proyecto-api-shop-spring-boot-hibernate-postgres-sql-docker}
  expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none