spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopapi
    username: shopapi
    password: shopapi
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  secret: "proyecto-api-shop-spring-boot-hibernate-postgres-sql-docker"
  expiration: 86400000

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none